### ISSUE TITLE
Strange crash in movie modal

### ISSUE THREAD

**Issue by astingraye** [Dark-Alex-17/managarr#15]
### Summary

I'm not 100% sure what causes this, and i often can't reproduce, but it occurs in the "movie info" modal. Frequently switching between the tabs may have something to do with it, i was on a pretty low end, low network speed laptop at the time

### Reproduction Steps

1. `managarr`
2. Press enter on any movie
3. Rapidly switch between the modal tabs before information loads (?)

### Managarr log

Crash Log

"name" = "managarr"
"operating_system" = "Arch Linux [64-bit]"
"crate_version" = "0.2.1"
"explanation" = """
Panic occurred in file '/home/raye/.cargo/registry/src/index.crates.io-6f17d22bba15001f/managarr-0.2.1/src/ui/radarr_ui/library/movie_details_ui.rs' at line 307
"""
"cause" = "called `Option::unwrap()` on a `None` value"
"method" = "Panic"
"backtrace" = """

   0: 0x632262bbe238 - core::option::unwrap_failed::h9c9d9ca460059c56
   1: 0x632262d6862f - managarr::ui::radarr_ui::library::movie_details_ui::draw_movie_info::h2b8f8070ca6e04ba
   2: 0x632262d5bb0e - <managarr::ui::radarr_ui::library::movie_details_ui::MovieDetailsUi as managarr::ui::DrawUi>::draw::h7bca17fc1be5aad5
   3: 0x632262d83648 - managarr::ui::ui::h2359d1c91a6184e1
   4: 0x632262d8a382 - managarr::start_ui::{{closure}}::ha783f42136a9288b
   5: 0x632262dd66ef - managarr::main::{{closure}}::hc7d79cd86adcaad5
   6: 0x632262dd4e3b - managarr::main::hc84e292f99db127b
   7: 0x632262bebe73 - std::sys::backtrace::__rust_begin_short_backtrace::he327880be41068f3
   8: 0x632262de7ae3 - main
   9: 0x7204b3634e08 - <unresolved>
  10: 0x7204b3634ecc - __libc_start_main
  11: 0x632262bd2e45 - _start
  12:        0x0 - <unresolved>"""

### Platform

Arch Linux 64 Bit

### Terminal Emulator

No DE Or Emulator, just base tty

### Managarr Version

Managarr 0.2.1 (Cargo)

**Comment by Dark-Alex-17** [comment]
Looks like your guess was right on the money. I was able to reproduce this as well by just opening a film's details and quickly changing tabs. I've started working on a fix and I'll update you once I have something working.

**Comment by Dark-Alex-17** [comment]
I've addressed the bug and found a few others while I was at it. I'll do a new release now since these are bugs that can all crash the application. Thanks for the detail and for reporting this!

**Comment by Dark-Alex-17** [comment]
Alright! I just released v0.2.2, so let me know if you can still reproduce this.

**Comment by Amcro** [comment]
I think i'm having same crash when spamming tab between radar/sonarr instance. I'm on latest versrion of Managarr.

```
"name" = "managarr"
"operating_system" = "Debian 12.0.0 [64-bit]"
"crate_version" = "0.4.0"
"explanation" = """
Panic occurred in file 'src/ui/radarr_ui/library/mod.rs' at line 99
"""
"cause" = "called `Option::unwrap()` on a `None` value"
"method" = "Panic"
"backtrace" = """
   0:     0x148839e0106c - rust_begin_unwind
   1:     0x1488396dcf3f - core::panicking::panic_fmt::h8143c7df49e27964
   2:     0x1488396dcfeb - core::panicking::panic::h297786ff165ce809
   3:     0x1488396dd368 - core::option::unwrap_failed::hf1dd19e7529df50b
   4:     0x1488399bf864 - managarr::ui::radarr_ui::library::draw_library::hef3c0d0b038a74bd
   5:     0x1488399ce077 - <managarr::ui::radarr_ui::RadarrUi as managarr::ui::DrawUi>::draw::h3d6615404cd4636c
   6:     0x148839a40dae - managarr::ui::ui::h4a56635a37c52f3c
   7:     0x148839a49827 - managarr::start_ui::{{closure}}::hc7688c363c45a4c9
   8:     0x148839b101b7 - managarr::main::{{closure}}::hc7deb98d5c7e8d59
   9:     0x148839b0e98b - managarr::main::h99ef9abe4c968348
  10:     0x148839714c83 - std::sys::backtrace::__rust_begin_short_backtrace::h6007a83f5ea7a977
  11:     0x148839b24c55 - main
"""
```

**Comment by Dark-Alex-17** [comment]
Does this happen on v0.4.1? I know we're talking in another thread about the update to 0.4.1 so I also want to check in on this.

**Comment by Amcro** [comment]
Yes, I can confirm it's still happening on 0.4.1

![image](https://github.com/user-attachments/assets/023c728c-2715-4e32-9941-5864e73e7cb5)

Still doing same thing, spamming tab between instances (Radarr, Sonarr) crashes Managarr. Not sure if it's related to Sonarr not working problem though.

**Comment by Dark-Alex-17** [comment]
Does this still happen with the config updates?

**Comment by Amcro** [comment]
Yes, unfortunately still crashing even with Sonarr working properly. I guess not everything is that simple lol

**Comment by Dark-Alex-17** [comment]
Okay I'm able to recreate it now. I'm not sure this is the same issue, as the one mentioned by @astingraye, however I have an idea.

**Comment by Dark-Alex-17** [comment]
Yep this was an issue with the cancellation token. I've updated it and pushed out the changes. This fix will go into the v0.4.2 release. Thanks for finding this!
