### ISSUE TITLE
Error connecting sonarr instance

### ISSUE THREAD

**Issue by Amcro** [Dark-Alex-17/managarr#26]
### Summary

When I open Managarr TUI I get UI with Radarr and Sonarr tabs. After I switch to Sonarr tab i get this error:

![image](https://github.com/user-attachments/assets/e7e5e620-6990-42c5-ae6b-e25a03ab127c)

In config I have exact same setup for Sonarr and Radarr
```
radarr:
  host: radarr
  port: 7878
  api_token: My-API-Token
sonarr:
  uri: sonarr
  port: 8989
  api_token: My-API-Token
```
Everything works properly for Radarr, but Sonarr keeps showing this error. I've double checked API key just to be sure, tried to change from "sonarr" URI to IP address but I had exact same problem.
There is no report created so I don't have anything to upload as a log, I can only post this image.

### Platform

Linux/Unraid 

### Terminal Emulator

No emulator

### Managarr Version

Managarr 0.4.0

**Comment by Amcro** [comment]
Ok, I've just noticed Github has 0.4.1 release with Sonarr support, I'm currently on 0.4.0 with latest tag. I guess DockerHub doesn't have 0.4.1 release yet and that's why my Sonarr instance is not connecting.

**Comment by Dark-Alex-17** [comment]
Hey thanks for finding this. This is definitely a bug in the release flow. As much as I love GitHub actions, sometimes it's such a pain to test and you can't test certain things with `act` so you're bound to miss some stuff. I appreciate you letting me know about that!

I'm not positive the version conflict is the cause, but let's give it a shot! I just pushed out the proper version to Docker Hub so try pulling the newest version and see if you still run into that issue.

**Comment by Amcro** [comment]
Hey, thanks for pushing the update again, it looks like pulling image again did update properly to 0.4.1, but unfortunately that did not fix my problem with Sonarr. 
I've also checked for updates on Sonarr just to be sure i'm on latest version (currently on 4.0.11.2680-ls261 by linuxserver.io).
I know API on Sonarr works properly since it works well with Prowlarr and Overseerr.
I'd be glad to help you out in any way to a fix and provide you any information you need.

**Comment by Dark-Alex-17** [comment]
Sure thing! Glad that worked at least! 😂

Hmm... My first thought is to check the logs. 

Can you run `managarr tail-logs` in one terminal then start it in another and paste the logs here?

**Comment by Dark-Alex-17** [comment]
Ah wait, this is in unRaid, right? That may not work unless you mount a volume over the logs directory. 

The image is based on Debian, so the log directory should be `/root/.cache/managarr/`.

The log file is creatively named `managarr.log`.

**Comment by Amcro** [comment]
Ok, so i managed to mount the volume and checked the log. It just keeps spamming same error.

```
2024-12-17 20:52:15.325 <23325306669880> [INFO] src/network/sonarr_network.rs:1892 - Fetching Sonarr quality profiles
2024-12-17 20:52:15.350 <23325306669880> [DEBUG] src/network/mod.rs:172 - Creating RequestBuilder for resource: "sonarr/api/v3/qualityprofile"
2024-12-17 20:52:15.350 <23325306669880> [DEBUG] src/network/mod.rs:173 - Sending Get request to sonarr/api/v3/qualityprofile with body None
2024-12-17 20:52:15.350 <23325306669880> [ERROR] src/network/mod.rs:148 - Failed to send request. reqwest::Error { kind: Builder, source: RelativeUrlWithoutBase }
2024-12-17 20:52:15.450 <23325306669880> [ERROR] src/main.rs:155 - Encountered an error handling network event: Failed to send request. builder error 
2024-12-17 20:52:15.451 <23325306669880> [INFO] src/network/sonarr_network.rs:1812 - Fetching Sonarr language profiles
2024-12-17 20:52:15.500 <23325306669880> [DEBUG] src/network/mod.rs:172 - Creating RequestBuilder for resource: "sonarr/api/v3/language"
2024-12-17 20:52:15.500 <23325306669880> [DEBUG] src/network/mod.rs:173 - Sending Get request to sonarr/api/v3/language with body None
2024-12-17 20:52:15.501 <23325306669880> [ERROR] src/network/mod.rs:148 - Failed to send request. reqwest::Error { kind: Builder, source: RelativeUrlWithoutBase }
2024-12-17 20:52:15.601 <23325306669880> [ERROR] src/main.rs:155 - Encountered an error handling network event: Failed to send request. builder error 
2024-12-17 20:52:15.601 <23325306669880> [INFO] src/network/sonarr_network.rs:2218 - Fetching Sonarr tags
2024-12-17 20:52:15.651 <23325306669880> [DEBUG] src/network/mod.rs:172 - Creating RequestBuilder for resource: "sonarr/api/v3/tag"
2024-12-17 20:52:15.651 <23325306669880> [DEBUG] src/network/mod.rs:173 - Sending Get request to sonarr/api/v3/tag with body None
2024-12-17 20:52:15.651 <23325306669880> [ERROR] src/network/mod.rs:148 - Failed to send request. reqwest::Error { kind: Builder, source: RelativeUrlWithoutBase }
2024-12-17 20:52:15.751 <23325306669880> [ERROR] src/main.rs:155 - Encountered an error handling network event: Failed to send request. builder error 
2024-12-17 20:52:15.751 <23325306669880> [INFO] src/network/sonarr_network.rs:1929 - Fetching Sonarr root folders
2024-12-17 20:52:15.801 <23325306669880> [DEBUG] src/network/mod.rs:172 - Creating RequestBuilder for resource: "sonarr/api/v3/rootfolder"
2024-12-17 20:52:15.801 <23325306669880> [DEBUG] src/network/mod.rs:173 - Sending Get request to sonarr/api/v3/rootfolder with body None
2024-12-17 20:52:15.801 <23325306669880> [ERROR] src/network/mod.rs:148 - Failed to send request. reqwest::Error { kind: Builder, source: RelativeUrlWithoutBase }
2024-12-17 20:52:15.901 <23325306669880> [ERROR] src/main.rs:155 - Encountered an error handling network event: Failed to send request. builder error 
2024-12-17 20:52:15.902 <23325306669880> [INFO] src/network/sonarr_network.rs:1444 - Fetching Sonarr downloads
2024-12-17 20:52:15.951 <23325306669880> [DEBUG] src/network/mod.rs:172 - Creating RequestBuilder for resource: "sonarr/api/v3/queue"
2024-12-17 20:52:15.951 <23325306669880> [DEBUG] src/network/mod.rs:173 - Sending Get request to sonarr/api/v3/queue with body None
2024-12-17 20:52:15.952 <23325306669880> [ERROR] src/network/mod.rs:148 - Failed to send request. reqwest::Error { kind: Builder, source: RelativeUrlWithoutBase }
2024-12-17 20:52:16.052 <23325306669880> [ERROR] src/main.rs:155 - Encountered an error handling network event: Failed to send request. builder error 
2024-12-17 20:52:16.052 <23325306669880> [INFO] src/network/sonarr_network.rs:1877 - Fetching Sonarr disk space
2024-12-17 20:52:16.101 <23325306669880> [DEBUG] src/network/mod.rs:172 - Creating RequestBuilder for resource: "sonarr/api/v3/diskspace"
2024-12-17 20:52:16.102 <23325306669880> [DEBUG] src/network/mod.rs:173 - Sending Get request to sonarr/api/v3/diskspace with body None
2024-12-17 20:52:16.102 <23325306669880> [ERROR] src/network/mod.rs:148 - Failed to send request. reqwest::Error { kind: Builder, source: RelativeUrlWithoutBase }
2024-12-17 20:52:16.202 <23325306669880> [ERROR] src/main.rs:155 - Encountered an error handling network event: Failed to send request. builder error 
2024-12-17 20:52:16.202 <23325306669880> [INFO] src/network/sonarr_network.rs:2202 - Fetching Sonarr system status
2024-12-17 20:52:16.252 <23325306669880> [DEBUG] src/network/mod.rs:172 - Creating RequestBuilder for resource: "sonarr/api/v3/system/status"
2024-12-17 20:52:16.252 <23325306669880> [DEBUG] src/network/mod.rs:173 - Sending Get request to sonarr/api/v3/system/status with body None
2024-12-17 20:52:16.252 <23325306669880> [ERROR] src/network/mod.rs:148 - Failed to send request. reqwest::Error { kind: Builder, source: RelativeUrlWithoutBase }
2024-12-17 20:52:16.352 <23325306669880> [ERROR] src/main.rs:155 - Encountered an error handling network event: Failed to send request. builder error 
2024-12-17 20:52:16.353 <23325306669880> [INFO] src/network/sonarr_network.rs:1892 - Fetching Sonarr quality profiles
2024-12-17 20:52:16.402 <23325306669880> [DEBUG] src/network/mod.rs:172 - Creating RequestBuilder for resource: "sonarr/api/v3/qualityprofile"
2024-12-17 20:52:16.402 <23325306669880> [DEBUG] src/network/mod.rs:173 - Sending Get request to sonarr/api/v3/qualityprofile with body None
2024-12-17 20:52:16.403 <23325306669880> [ERROR] src/network/mod.rs:148 - Failed to send request. reqwest::Error { kind: Builder, source: RelativeUrlWithoutBase }
2024-12-17 20:52:16.502 <23325306669880> [ERROR] src/main.rs:155 - Encountered an error handling network event: Failed to send request. builder error 
2024-12-17 20:52:16.503 <23325306669880> [INFO] src/network/sonarr_network.rs:1812 - Fetching Sonarr language profiles
2024-12-17 20:52:16.552 <23325306669880> [DEBUG] src/network/mod.rs:172 - Creating RequestBuilder for resource: "sonarr/api/v3/language"
2024-12-17 20:52:16.553 <23325306669880> [DEBUG] src/network/mod.rs:173 - Sending Get request to sonarr/api/v3/language with body None
2024-12-17 20:52:16.553 <23325306669880> [ERROR] src/network/mod.rs:148 - Failed to send request. reqwest::Error { kind: Builder, source: RelativeUrlWithoutBase }
2024-12-17 20:52:16.653 <23325306669880> [ERROR] src/main.rs:155 - Encountered an error handling network event: Failed to send request. builder error 
2024-12-17 20:52:16.653 <23325306669880> [INFO] src/network/sonarr_network.rs:2218 - Fetching Sonarr tags
2024-12-17 20:52:16.703 <23325306669880> [DEBUG] src/network/mod.rs:172 - Creating RequestBuilder for resource: "sonarr/api/v3/tag"
2024-12-17 20:52:16.703 <23325306669880> [DEBUG] src/network/mod.rs:173 - Sending Get request to sonarr/api/v3/tag with body None
2024-12-17 20:52:16.703 <23325306669880> [ERROR] src/network/mod.rs:148 - Failed to send request. reqwest::Error { kind: Builder, source: RelativeUrlWithoutBase }
2024-12-17 20:52:16.803 <23325306669880> [ERROR] src/main.rs:155 - Encountered an error handling network event: Failed to send request. builder error 
2024-12-17 20:52:16.803 <23325306669880> [INFO] src/network/sonarr_network.rs:2180 - Fetching Sonarr library
2024-12-17 20:52:16.853 <23325306669880> [DEBUG] src/network/mod.rs:172 - Creating RequestBuilder for resource: "sonarr/api/v3/series"
2024-12-17 20:52:16.853 <23325306669880> [DEBUG] src/network/mod.rs:173 - Sending Get request to sonarr/api/v3/series with body None
2024-12-17 20:52:16.853 <23325306669880> [ERROR] src/network/mod.rs:148 - Failed to send request. reqwest::Error { kind: Builder, source: RelativeUrlWithoutBase }
2024-12-17 20:52:16.953 <23325306669880> [ERROR] src/main.rs:155 - Encountered an error handling network event: Failed to send request. builder error 
```

Same setup work for Radarr, not sure why it's not working for Sonarr, hope this helps.

**Comment by Dark-Alex-17** [comment]
Ah it took me a second to see it, but I see the error: Your config for Sonarr uses the `uri` field, which expects a full URI and ignores the port. Your Radarr config uses the `host` field, which can take relative URL's like `radarr` or `sonarr`. Try updating your config and see if that works.

**Comment by Amcro** [comment]
Ah, so sorry! Good catch, didn't even notice when i copy pasted from template. Changing to host solved the problem!

**Comment by Dark-Alex-17** [comment]
Hey, I'm just glad it was something that simple! That's always nice on my end of things :stuck_out_tongue:
