### ISSUE TITLE
unwrap on a None value

### ISSUE THREAD

**Issue by wolf39us** [Dark-Alex-17/managarr#42]
### Summary

Getting an error on Sonarr LSIO.  Latest version: 4.0.14.2939

### Reproduction Steps

I believe this might be some setting I have on my sonarr potentially.  I'm not 100% sure.  

I did analyze the error and poked around my sonarr instance to see if there was anything out of place.

I then created a new sonarr instance with binhex and it connected just fine.  That being said, I'd hate to rebuild my sonarr from scratch.  Any way to put some logging or error handling here so I can figure out what is happening?

### Managarr log

"name" = "managarr"
"operating_system" = "Debian 12.0.0 [64-bit]"
"crate_version" = "0.5.0"
"explanation" = """
Panic occurred in file 'src/ui/sonarr_ui/library/mod.rs' at line 122
"""
"cause" = "called `Option::unwrap()` on a `None` value"
"method" = "Panic"
"backtrace" = """
   0:     0x55db8012c81c - rust_begin_unwind
   1:     0x55db7fa2908f - core::panicking::panic_fmt::h896a0727a1a943f9
   2:     0x55db7fa290db - core::panicking::panic::h06336e0c962d4a4a
   3:     0x55db7fa293f8 - core::option::unwrap_failed::ha2239fe7bcf32a06
   4:     0x55db7fd4b57e - managarr::ui::sonarr_ui::library::draw_library::hd1027d4bf05d413a
   5:     0x55db7fd43523 - <managarr::ui::sonarr_ui::library::LibraryUi as managarr::ui::DrawUi>::draw::hfda06fae24af1e96
   6:     0x55db7fd75cc6 - managarr::ui::ui::h44937dae223add4e
   7:     0x55db7fd7f25c - managarr::start_ui::{{closure}}::h29db4c846ba43573
   8:     0x55db7fe314f6 - managarr::main::{{closure}}::h35d9e9667a26874f
   9:     0x55db7fe2fc2b - managarr::main::h454a422e5ada29f5
  10:     0x55db7fa5b283 - std::sys::backtrace::__rust_begin_short_backtrace::h5b1f738d4d18f19a
  11:     0x55db7fe46be4 - main
  12:     0x14ba60e8c24a - <unresolved>
  13:     0x14ba60e8c305 - __libc_start_main
  14:     0x55db7fa3d781 - _start
  15:                0x0 - <unresolved>
"""

### Platform

unRAID - Docker

### Terminal Emulator

.

### Managarr Version

managarr 0.5.0

**Comment by Dark-Alex-17** [comment]
Hmm interesting. That panic is being caused specifically by Managarr trying to correlate a tag on a series to its name.

The Sonarr API represents tags as separate entities from the things which are tagged (which makes sense). So for a series, it will have a tag ID associated with it instead of the actual direct tag name.

So a series entity will look like this:

`Series(tag_id)` which corresponds to `Tag(tag_id, tag_name)`

This is how Managarr uses the Sonarr API to fetch the names of tags when attempting to display them in the main `Library` table.

The panic is being caused by the fact that somehow, one of the series in your library has a tag ID associated with it that doesn't actually correspond to a specific tag returned by the tags endpoint.

Double check your series and see if maybe you have one that has a tag associated with it, but you don't use that tag anywhere else or maybe even deleted the tag entirely.

This could potentially be a bug within Sonarr itself since I don't think you should ever have a tag ID that isn't associated with an existing tag.

**Comment by wolf39us** [comment]
> Hmm interesting. That panic is being caused specifically by Managarr trying to correlate a tag on a series to its name.
> 
> The Sonarr API represents tags as separate entities from the things which are tagged (which makes sense). So for a series, it will have a tag ID associated with it instead of the actual direct tag name.
> 
> So a series entity will look like this:
> 
> `Series(tag_id)` which corresponds to `Tag(tag_id, tag_name)`
> 
> This is how Managarr uses the Sonarr API to fetch the names of tags when attempting to display them in the main `Library` table.
> 
> The panic is being caused by the fact that somehow, one of the series in your library has a tag ID associated with it that doesn't actually correspond to a specific tag returned by the tags endpoint.
> 
> Double check your series and see if maybe you have one that has a tag associated with it, but you don't use that tag anywhere else or maybe even deleted the tag entirely.
> 
> This could potentially be a bug within Sonarr itself since I don't think you should ever have a tag ID that isn't associated with an existing tag.

Thanks for the prompt response.

I deleted all tags assigned as well as in Settings > Tags.  Unfortunately, it didn't correct the problem.

That being said, I only had about 100 entries, so I deleted all of them and reimported.  The problem is now corrected.  Maybe a SQL error somewhere?  Not sure.

**Comment by Dark-Alex-17** [comment]
I'm glad that worked! But I'm sorry you had to wipe everything to get it working. I've just pushed a change to make the Sonarr and Radarr UI's more fault tolerant about this particular issue, just in case. 

This fix will be in the next release.

I'm going to dig through the Sonarr codebase and see if I can figure out what's happening and open a ticket to fix it if I find anything. Otherwise, it might be that my base assumptions about how Sonarr creates/manages tags across resources is just plain wrong (hopefully that's not true though...)

**Comment by Dark-Alex-17** [comment]
This fix was just released! Let me know if  you still experience issues and we can reopen this issue!
